Correct errors and expand labels for clarity
ArduPilot/CustomBuild pull request #18
Opened 2021-09-28 21:53 UTC by Hwurzburg

since there is no CI, my typing dyslexia needs to be reviewed carefully

2021-09-29 02:04 UTC, nkruzan commented
@Hwurzburg looks ok to me. Might also capitalize AHRS under Other "Enable External ahrs"...(or remove it from other as it's redundant)

2021-09-29 23:44 UTC, Hwurzburg commented
removed it

2021-10-04 23:03 UTC, tridge requested changes

2021-10-04 23:03 UTC, tridge commented on app.py
> +    Feature('Telemetry', 'CRSF', 'HAL_CRSF_TELEMETRY_ENABLED', 'Enable CRSF Telemetry', 0, None),
i think this is HAL_CRSF_TELEM_ENABLED

2021-10-04 23:03 UTC, tridge commented on app.py
> +    Feature('Telemetry', 'CRSFText', 'HAL_CRSF_TEXT_SELECTION_ENABLED', 'Enable CRSF Text Param Selection', 0, 'CRSF'),
should be HAL_CRSF_TELEM_TEXT_SELECTION_ENABLED

2021-10-05 02:56 UTC, tridge approved these changes

2021-10-05 02:56 UTC, merged